### ISSUE TITLE
add display_names variable for creating multiple service accounts with different display names.

### ISSUE THREAD

**Issue by stevesea** [terraform-google-modules/terraform-google-service-accounts#86]
### TL;DR

when creating multiple accounts, there are separate variables to use -- `names`, `descriptions`. But, the same display_name is used for every account. 

There are places in GCP Console where the display_name is used (Enabled APIs & Services -> Bigtable API -> metrics -> traffic by credential), and the legend of the chart shows N service accounts as 'Terraform-managed service account'. 

### Detailed design

```markdown
I assume the implementation for this would be similar to var.descriptions 

  display_name  = index(var.names, each.value) >= length(var.display_names) ? var.display_name : element(var.display_name, index(var.names, each.value))
```

**Comment by pataquets** [comment]
+1 for this FR, for the feature need and also for consistency.
@q2w, @bharathkkb, @apeabody: I was about to file a new issue for the exact same FR. This was closed as "not planned" but I'm unsure if that was meant that way or just the default stalebot status.
Apparently, this was also worked on at #99, but it got closed due to staleness. @dkuji: are you still interested/available to push this forward or are you OK with sb else picking it up?

**Comment by dkuji** [comment]
@pataquets
I missed comment in the closed PR.
I've recreated the PR #163.
